name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run unit

      - name: Typescript
        run: npm run typescript

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Auto Merge
        uses: actions/github-script@v3
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          github-token: ${{secrets.github_token}}
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
